apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: java-functions-demo
spec:
  template:
    spec:
      containers:
        # Replace with your docker registry info
        - image: 665986443982.dkr.ecr.ap-northeast-1.amazonaws.com/java-functions-demo:latest
          ports:
            - containerPort: 80
