apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: java-functions-demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "150"
    spec:
      containers:
        - image: 665986443982.dkr.ecr.ap-northeast-1.amazonaws.com/java-functions-demo:latest
          imagePullPolicy: Always
